
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class DownloadTruyen extends javax.swing.JFrame {

    /**
     * Creates new form GetAllChapter
     */
    public DownloadTruyen() {
        initComponents();
        process.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnDownload = new javax.swing.JButton();
        process = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa = new javax.swing.JTextArea();
        DownWithSartPage1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Get ALL Chapter");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("URL Story");

        btnDownload.setText("DownloadItem");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        txa.setColumns(20);
        txa.setRows(5);
        jScrollPane1.setViewportView(txa);

        DownWithSartPage1.setText("DownWithSartPage1");
        DownWithSartPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownWithSartPage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DownWithSartPage1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDownload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DownWithSartPage1)
                        .addGap(34, 34, 34)))
                .addComponent(process, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int i = 0;
    int j = 0;
    boolean flag = true;
    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
       // ChapterCollect chapterCollect = new ChapterCollect();
        // chapterCollect.getAllChapter(txtUrl.getText(),process,txa);
        flag = true;
        txa.setText("");
        i = 0;
        Thread t1 = new Thread() {
            @Override
            public void run() {
                while (flag) {
                    try {
                        process.setValue(i);
                        i++;
                        if (i == process.getMaximum()) {
                            i = 0;
                        }
                        Thread.sleep(100);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(DownloadTruyen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        };
        Thread t2 = new Thread() {
            @Override
            public void run() {

                ChapterCollect chapterCollect = new ChapterCollect();
                chapterCollect.getAllChapter(txtUrl.getText(), txa);
                flag = false;
                process.setValue(process.getMaximum());
            }

        };

        t1.start();
        t2.start();
    // ChapterCollect chapterCollect = new ChapterCollect();
        // chapterCollect.getAllChapter(txtUrl.getText(),txa);

     //flag = false;
    // txa.append("DONE!");

    }//GEN-LAST:event_btnDownloadActionPerformed

    private void DownWithSartPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownWithSartPage1ActionPerformed
        flag = true;
        txa.setText("");
        i = 0;
        Thread t3 = new Thread() {
            @Override
            public void run() {
                while (flag) {
                    try {
                        process.setValue(i);
                        i++;
                        if (i == process.getMaximum()) {
                            i = 0;
                        }
                        Thread.sleep(100);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(DownloadTruyen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        };
        Thread t4 = new Thread() {
            @Override
            public void run() {

                ChapterCollect chapterCollect = new ChapterCollect();
                chapterCollect.startWithPage1(txtUrl.getText(), txa);
                flag = false;
                process.setValue(process.getMaximum());
            }

        };

        t3.start();
        t4.start();

    }//GEN-LAST:event_DownWithSartPage1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadTruyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadTruyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadTruyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadTruyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadTruyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownWithSartPage1;
    private javax.swing.JButton btnDownload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar process;
    private javax.swing.JTextArea txa;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
